### ISSUE TITLE
What I used

### ISSUE THREAD

**Issue by ChristopherKing42** [zenorogue/newconformist#1]
Regarding "we do not know what algorithm he has been using", I used the JacobiSN function built in to the wolfram open cloud to conformally map a rectangle to a circle. In particular, I used JacobiSn(x, k) (where k depends on the aspect ratio of the rectangle) to map the rectangle to the half plane and I used x -> (x + i)/(i x + 1) to map the half plane to the disk. I can share the code if anyone is interested.

**Comment by zenorogue** [comment]
Thanks for explaining! Added a link to this description to readme.
